apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-web-config
data:
  config.php: |
    <?php
    $host = getenv('muhanrds.cxqu2e2cg5ww.ap-northeast-2.rds.amazonaws.com');  
    $dbname = getenv('hospital)_db');
    $username = getenv('admin');
    $password = getenv('ehddnr99!');

    try {
        $pdo = new PDO("mysql:host=$host;dbname=$dbname;charset=utf8", $username, $password);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    } catch (PDOException $e) {
        die("Database connection failed: " . $e->getMessage());
    }
    ?>
