apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-web-config
data:
  config.php: |
    <?php
    $host = getenv('DB_HOST');  // 환경 변수에서 값 가져오기
    $dbname = getenv('DB_NAME');
    $username = getenv('DB_USER');
    $password = getenv('DB_PASSWORD');

    try {
        $pdo = new PDO("mysql:host=$host;dbname=$dbname;charset=utf8", $username, $password);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    } catch (PDOException $e) {
        die("Database connection failed: " . $e->getMessage());
    }
    ?>
