name: Deploy to EKS

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 워크플로우 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: 'ap-northeast-2'  # ECR 리전 설정

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AWS_ECR_REGISTRY }}/hospital:latest .

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/hospital:latest

      - name: Set up kubectl
        uses: aws-actions/configure-kubectl@v2  # v2로 버전 업데이트
        with:
          region: 'ap-northeast-2'  # EKS 리전 설정

      - name: Deploy to EKS
        run: |
          kubectl apply -f kubernetes/deployment.yaml
